higress-group/higress-standalone

bin/shutdown.sh, bin/startup.sh
Fix the issue that built-in nacos isn't started when manually calling startup.sh.
=> fix: Fix re-start issue when using built-in nacos

compose/scripts/init.sh, compose/scripts/precheck.sh
Reason: Just in case auth isn't enabled in nacos actually and user made a wrong configuration.
=> fix: Ignore errors of failed to get access token from nacos

compose/docker-compose.yml, compose/env/gateway.env, compose/scripts/init.sh
1. Selectors in WasmPlugin resources generated by Higress Controller seems to be `namespace.name` at all time. So change the gateway selector labels to meet the requirement.
2. Add POD_NAME and POD_NAMESPACE environment variables to normalize the proxyID values logged by the pilot.
3. Mount a writable volume to `/var/lib/istio/data` in gateway container for storing downloaded Wasm plugins.
=> fix: Fix the malfunction of Wasm plugins

README.md, bin/configure.sh, compose/scripts/init.sh, src/get-higress.sh, test/configure/cases/args-file-full_non-windows.inc, test/configure/cases/args-file-path-relative_non-windows.inc, test/configure/cases/args-file-path-relative_windows.inc, test/configure/cases/args-file-path-with-colon_windows.inc, test/configure/cases/input-file-full_non-windows.inc, test/configure/cases/input-file-relative-path_non-windows.inc, test/configure/cases/input-file-relative-path_windows.inc
Fix some bugs in shell scripts:
1. Fix the incorrect format of file:// URLs supported in configuration
Supported formats: 
- file:///opt/higress/data
- file://./higress/data
- file:///c/temp/higress/data
- file:///c:/opt/higress/data
2. Always create a default McpBridge resource for editing
3. Exclude the test folder when decompressing during installation
=> fix: Fix some bugs in shell scripts

compose/scripts/init.sh, src/apiserver/Makefile, src/apiserver/pkg/apiserver/apiserver.go, src/apiserver/pkg/cmd/server/start.go, src/apiserver/pkg/options/options.go
1. Extend the validity of certificates used by API server to 100 years.
2. Disable the authentication and authorization features on API server by default.
Note: After disabling authN and authZ of API server, the validity of cerificates won't matter at all. The validity of 100 years is just in case.
=> fix: Fix the authentication failure one month later after the installation

src/get-higress.sh
If anything goes wrong during the configuration phase of the standalone deployment, and user tries to reinstall Higress, an "update with -u" prompt would be shown.
However, Higress is not in fact "installed" in the target folder. So we use the "compose/.configured" file to determine whether the configuration phase has finished successfully or not, and only show the update prompt if configured.
=> fix: No update prompt if the target folder contains an unconfigured Higress instance

bin/configure.sh, bin/reset.sh, src/get-higress.sh
Allow separating the config workflow into two phases: prepare and init, so hgctl can know which phase goes wrong and deal the problem properly.
=> feat: Separate the config workflow into two phases: prepare and init

compose/scripts/init.sh, compose/scripts/precheck.sh
since we have already had the secret initialization logic in the Console itself.
=> fix: Remove the higress console secret initialization and precheck logic

compose/scripts/init.sh
just in case user installs a second Higress instance to the same Nacos server and namespace.
```bash
publishConfig() {
case $CONFIG_STORAGE in
nacos)
publishNacosConfig "$@"
;;
file)
publishFileConfig "$@"
;;
*)
printf "  Unknown storage type: %s\n" "$CONFIG_STORAGE"
exit -1
;;
esac
}
```
=> fix: Not to overwrite any existed configurations in Nacos during initialization

src/apiserver/pkg/options/options.go, src/apiserver/pkg/registry/nacos_rest.go, src/apiserver/pkg/utils/env.go
1. Skip the __names__ item when enumerating all configs
2. Allow changing some Nacos options via environment variables
3. Use local Nacos config cache as a fallback by default
=> fix: Fix some errors in nacosREST

all-in-one/scripts/start-apiserver.sh
especially when running in docker compose.
fixes #70
=> fix: Not to break the start-up process if higress-console ingress has been deleted already

all-in-one/Dockerfile, all-in-one/config/mcpbridges/default.yaml, all-in-one/scripts/config-template/ai-proxy.sh, all-in-one/scripts/start-apiserver.sh, all-in-one/scripts/start-gateway.sh
```shell
-e CONFIG_TEMPLATE=ai-proxy
-e AZURE_OPENAI_SERVICE_URL="https://xxx.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2024-02-15-preview"
-e AZURE_OPENAI_API_KEY="xxx"
-e DASHSCOPE_API_KEY="sk-yyy"
-e MOONSHOT_API_KEY="sk-zzz"
-e OPENAI_API_KEY="kkk"
```
=> feat: Add ai-proxy config template support to the AiO image

src/apiserver/pkg/options/options.go
Enable rolling for Nacos log files by default with following arguments:
- MaxAge=3d
- MaxSize=30MB
- MaxBackups=3
fixes https://github.com/alibaba/higress/issues/1594
=> feat: Enable rolling for Nacos log files.

src/apiserver/go.mod, src/apiserver/go.sum
In the previously referenced version of Higress, the type of `WasmPlugin.DefaultConfigDisable` is `bool` with `json:"omitempty"` tag, causing `false` value being omitted during serialization.
Now its type is changed to `*wrappers.BoolValue` to fix this problem.
=> fix: Update higress dependency to fix a WasmPlugin serialization issue

src/apiserver/pkg/registry/file_rest.go, src/apiserver/pkg/registry/nacos_rest.go
Otherwise, when using Nacos as the storage and deleting an inexist resource, a 500 error will be returned.
=> fix: Adjust some status codes returned by API when delete operation fails

src/apiserver/pkg/registry/file_rest.go, src/apiserver/pkg/registry/nacos_rest.go
Use watcher list length as watcher id could lead to duplicate watcher id, then the exist watcher will lost. This could happen when some watcher stopped and new watcher create.
1. create two watcher.
id: 0
id: 1
2. watcher with id 0 stopped，watcher list length is 1 now.
https://github.com/higress-group/higress-standalone/blob/1d580382d72e6a8bd01436aa6280cdc0a98ce762/src/apiserver/pkg/registry/file_rest.go#L689-L693
3. create new watcher, it's id is the watcher list length 1, which is duplicate with existing watcher.
https://github.com/higress-group/higress-standalone/blob/1d580382d72e6a8bd01436aa6280cdc0a98ce762/src/apiserver/pkg/registry/file_rest.go#L644-L649
=> fix: duplicate watcher id

all-in-one/Dockerfile, all-in-one/config/configmaps/higress-config.yaml, all-in-one/scripts/start-apiserver.sh
During start-up, extract the content of mesh configs (`mesh` and `meshNetworks`) in `higress-config.yaml` file into `/etc/istio/config` dir. So user can modify them by changing the content of `higress-config.yaml`.
=> feat: Support modifying mesh config files in all-in-one images

all-in-one/scripts/start-gateway.sh, compose/docker-compose.yml
1. Support customizing gateway concurrency.
2. Unify the default gateway concurrency to 16.
fixes https://github.com/alibaba/higress/issues/2299
Add `-e GATEWAY_CONCURRENCY=xx` to the `docker run` command.
Modify the `--concurrency` command line arg of gateway service in `docker-compose.yml`.
=> feat: Support customizing gateway concurrency

src/apiserver/pkg/registry/file_rest.go
When processing resource update requests, only check the `resourceVersion` field with the current `resourceVersion` value when the value in the request is not empty.
The Nacos storage implementation behaves like this now. This PR changes the behavior in the implementation of file storage.
https://github.com/higress-group/higress-standalone/blob/main/src/apiserver/pkg/registry/nacos_rest.go#L358
=> fix: Unify resourceVersion check logic

all-in-one/supervisord/supervisord.conf
Use fixed `POD_NAMESPACE` and `POD_NAME` envs when starting controller in `all-in-one` image, just in case that the image is deployed in a K8s cluster with these two envs injected by the K8s, causing controller only accepts the default `McpBridge` resource in that namespace.
=> fix: Fix some envs when starting controller to avoid conflicts
